root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "testdata"]
delay = 1000 # Delay in milliseconds before rebuilding
full_bin = "./tmp/main"

[log]
time = true

[misc]
clean_on_exit = true